spring:
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ec201804b@gmail.com
    password: kknfrvthynvamnfu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            #enable: false
            enable: true
          socketFactory:
            #port: 2525
            port: 587

            fallback: false
        debug: true
    test-connection: false
  datasource:
    driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-201804b
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jmx:
    default-domain: ec-201804b #複数のアプリを１つのサーバ上で動かす際に必要な設定
server:
  servlet:
      context-path: /ec-201804b
